version: '3'
services:
  front:
    image: mspd22/react_app_with_sso:front-latest
    ports:
      - 3000:3000
    container_name: react-container
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-stack-network
    volumes:
      - ./client:/app
    depends_on:
      - backend

  backend:
    image: mspd22/react_app_with_sso:backend-latest
    ports:
      - 5500:5500
    container_name: express-container
    networks:
      - mern-stack-network
    volumes:
      - ./api:/app
    depends_on:
      - mongo

  mongo:
    image: mspd22/react_app_with_sso:mongo-latest
    ports:
      - 27017:27017
    container_name: mongo-container
    networks:
      - mern-stack-network
    volumes:
      - mongoData:/data/db

networks:
  mern-stack-network:
volumes:
  mongoData:
